name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test and Coverage
        run: |
          go test -v -coverprofile cover.out ./...
          COVERAGE="$(go tool cover -func=cover.out | grep total: | grep -Eo '[0-9]+\.[0-9]+')"
          echo $COVERAGE
          COLOR=orange
          if (( $(echo "$COVERAGE <= 50" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$COVERAGE > 90" | bc -l) )); then
            COLOR=green
          fi
          curl "https://img.shields.io/badge/coverage-$COVERAGE%25-$COLOR" > badge.svg

      - name: Upload badge
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: badge.svg
          path: badge.svg